export const ERROR_CODES = {
    TOO_MANY_REQUESTS: 'E000',
    GENERAL_ERROR: 'E001',
    INVALID_JSON_CONFIG: 'E002',
    ROUTE_NOT_FOUND: 'E003',
    UNAUTHORIZED: 'E004',
    NOT_FOUND: 'E005',
    INTERNAL_ERROR: 'E006',
    RANGE_NOT_SATISFIABLE: 'E007',
    BAD_REQUEST: 'E008',
};
